Repository codestates-seb/seb40_main_028, pull requests merged in 2022-12, with the labels that each got.

#132 📝 자체 회원가입, 등록 MemberController 테스트 코드 작성 및 Spring Rest Docs API 문서에 회…
  server/src/docs/asciidoc/index.adoc
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/member/MemberProgressControllerTest.java
Labels: documentation, be_test

#135 :memo: 마이페이지 개인 정보 수정 Controller 테스트 코드 작성 및 Spring Rest Docs API 문서에 마이페이지 개인 정보 수정 API 내용 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java
Labels: documentation, be_test

#136 :memo: 마이페이지 비밀번호 수정 Controller 테스트 코드 작성 및 Spring Rest Docs API 문서에 마이 페이지 비밀번호 수정 API 내용 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/seb028/guenlog/member/dto/PasswordPatchDto.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java
Labels: documentation, be_test

#138 :white_check_mark:운동 진행 조회/완료, 마이페이지 조회, 개인정보 조회, 수정 테스트시 ResponseBody 검증 테스트 추가
  server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
  server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java
Labels: documentation, be_test

#139 :fire: 불필요한 컨트롤러 테스트 클래스 삭제
  server/src/test/java/com/seb028/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
Labels: be_test

#143 :sparkles: git actions 자동 배포 파일 추가
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
  server/src/main/resources/application.yml
Labels: be-dev

#146 ⚡️ Plan 페이지 로딩처리
  client/package-lock.json
  client/src/components/Plan/Modals/PlanModal.jsx
  client/src/pages/Plan.jsx
  client/src/state/states.jsx
Labels: fe-dev

#147 🐛 일일 클릭시 렉걸리는 오류 수정
  client/src/components/Main/MainCalendar.jsx
Labels: fe-dev

#144 📝 회원 추가정보 입력, 회원 삭제 MemberController 테스트 코드 작성 및 Spring Rest Docs API…
  server/src/docs/asciidoc/index.adoc
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/member/MemberProgressControllerTest.java
Labels: documentation, be_test

#149 🎨페이지 개선2
  client/public/android-icon-192x192.png
  client/public/index.html
  client/public/manifest.json
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
Labels: fe-dev

#150 🐛 TokenValue -> TokenState 수정 작업
  client/src/components/Main/MainCalendar.jsx
  client/src/components/Main/YouTubeContainer.jsx
  client/src/components/Plan/Modals/DetailContent.jsx
  client/src/components/Plan/Modals/DetailEdit.jsx
  client/src/components/Plan/PlanAdd.jsx
  client/src/pages/Plan.jsx
Labels: fe-dev

#151 ⚡️ 성능 개선 : 로고 수정
  client/src/assets/img/Logo.png
Labels: fe-dev

#152 🎨페이지 수정
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
Labels: fe-dev

#154 🔧 프론트 임시 배포 서버 주소로 OAuth2 리다이렉트 URI 수정
  server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java
Labels: be-dev

#156 🐛 Axios HTTP -> HTTPS 로 수정
  client/src/components/Main/MainCalendar.jsx
  client/src/components/Main/YouTubeContainer.jsx
  client/src/components/Plan/Modals/DetailContent.jsx
  client/src/components/Plan/Modals/DetailEdit.jsx
  client/src/components/Plan/PlanAdd.jsx
  client/src/pages/NotFound.jsx
  client/src/pages/Plan.jsx
Labels: fe-dev

#155 🐛 workout 페이지 http https로 수정
  .gitignore
  client/package.json
  client/src/pages/Workout.jsx
Labels: fe-dev

#158 🐛 URL env변수로 변경
  client/src/pages/Workout.jsx
Labels: fe-dev

#160 🎨페이지 수정
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/PwModal.jsx
  client/src/components/Mypage/SecessionModal.jsx
  client/src/pages/Mypage.jsx
Labels: fe-dev

#162 🐛 카테고리 이미지 추가
  client/src/components/Plan/Modals/CategorieContent.jsx
Labels: fe-dev

#163 🐛 글씨 잘리는것 버그픽스
  client/src/components/exercise/ExerciseButton.jsx
  client/src/pages/Workout.jsx
Labels: fe-dev

#165 🎨 URL 구조 변경
  client/src/pages/Workout.jsx
Labels: fe-dev

#169 🔧 프론트 최종 배포 서버 주소로 OAuth2 리다이렉트 URI 수정
  server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java
Labels: be-dev

#172 🐛맵 페이지 버그 수정
  client/src/components/Map/SearchPlace.jsx
Labels: fe-dev

#174 ⚡️ Login & Register UI 수정
  client/src/components/LoginContainer.jsx
  client/src/components/MainLogo.jsx
  client/src/components/RegisterContainer.jsx
  client/src/pages/Login.jsx
  client/src/pages/Register.jsx
  client/src/pages/Start.jsx
Labels: fe-dev

#175 🐛 Start, Login, Register 페이지 애니메이션 추가 및 달력 버그픽스
  client/src/components/InformationContainer.jsx
  client/src/components/LoginContainer.jsx
  client/src/components/Main/MainCalendar.jsx
  client/src/components/RegisterContainer.jsx
  client/src/pages/Start.jsx
Labels: fe-dev

#177 ⚡️ 현재날짜계산 수정, 에러코드 추가대응, 시간기록 미세수정
  client/src/pages/Workout.jsx
Labels: fe-dev

#179 🐛마이페이지 버그 수정
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
Labels: fe-dev

#180 🐛 console.log 제거 및 버그수정
  client/src/components/exercise/Congrats.jsx
  client/src/pages/Workout.jsx
Labels: fe-dev

#181 🔥 console.log 및 env 주석 삭제
  client/README.md
  client/src/components/InformationContainer.jsx
  client/src/components/LoginContainer.jsx
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/PwModal.jsx
  client/src/components/Plan/Modals/CategorieContent.jsx
  client/src/components/RegisterContainer.jsx
  client/src/pages/Logout.jsx
  client/src/pages/Oauth.jsx
  client/src/pages/Workout.jsx
Labels: fe-dev

#182 📌 불필요한 함수 제거
  client/src/components/exercise/Congrats.jsx
  client/src/pages/Workout.jsx
Labels: fe-dev

#184 🚑운동 계획 존재할 때 회원 탈퇴 안되는 버그 픽스, OAuth2 리다이렉트 URI 수정
  server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java
  server/src/main/java/com/seb028/guenlog/exercise/entity/Record.java
  server/src/main/java/com/seb028/guenlog/exercise/entity/Today.java
  server/src/main/java/com/seb028/guenlog/member/entity/Member.java
Labels: bug, be-dev

#186 🐛마이페이지 버그 수정
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageText.jsx
  client/src/components/Mypage/MyPageText2.jsx
Labels: fe-dev

#187 자동배포 파일 수정 및 rest docs 문서화 추가
  .github/workflows/gradle.yml
  appspec.yml
  server/scripts/deploy.sh
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExercisePlanController.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseMainControllerRestDocsTest.java
  server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExercisePlanControllerRestDocsTest.java
Labels: documentation, be-dev, be_test

#192 :zap: native query -> query dsl로 변경
  server/build.gradle
  server/src/main/java/com/seb028/guenlog/config/QuerydslConfiguration.java
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseMainController.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseMainResponseDto.java
  server/src/main/java/com/seb028/guenlog/exercise/service/ExerciseMainService.java
  server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseMainControllerRestDocsTest.java
Labels: enhancement, be-dev
