Repository codestates-seb/seb40_main_028, pull requests merged in 2022-11, with the labels that each got.

#1 ✨ Layout, Route 리펙토링 및 404페이지 추가
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Layout.js
  client/src/index.js
  client/src/pages/Main.js
  client/src/pages/Map.js
  client/src/pages/Mypage.js
  client/src/pages/NotFound.js
  client/src/pages/Plan.js
  client/src/pages/Workout.js
  client/src/reset.css
  client/src/routes/Routes.js
  client/tailwind.config.js
Labels: front-dev

#2 ✨ Plan 페이지 기반 작성, 그외 컴포넌트 약간 수정
  client/src/App.js
  client/src/components/Button.js
  client/src/components/Layout.js
  client/src/components/PlanButton.js
  client/src/components/PlanCalender.js
  client/src/components/PlanList.js
  client/src/pages/NotFound.js
  client/src/pages/Plan.js
  client/tailwind.config.js
Labels: front-dev

#3 ⚡️ Plan 디자인 임시 수정
  client/package-lock.json
  client/package.json
  client/src/components/Layout.js
  client/src/components/PlanButton.js
  client/src/components/PlanCalender.js
  client/src/components/PlanList.js
  client/src/pages/Plan.js
Labels: front-dev

#19 ✨ Plan 페이지 달력 추가
  client/package-lock.json
  client/package.json
  client/src/components/Layout.js
  client/src/components/PlanAdd.js
  client/src/components/PlanCalendar.js
  client/src/components/PlanCalender.js
  client/src/components/PlanList.js
  client/src/pages/Plan.js
Labels: fe-dev

#20 🐛 Plan 달력 아무곳 눌러도 나오게 버그픽스
  client/src/components/PlanCalendar.js
Labels: fe-dev

#21 ✨ Plan label for 버그수정, Modal 임시 생성
  client/src/components/PlanAdd.js
  client/src/components/PlanCalendar.js
  client/src/components/PlanModal.js
  client/src/pages/Plan.js
Labels: fe-dev

#27 :sparkles: 자체 회원 등록 기능 구현, 유효성 검사
  server/src/main/java/com/seb028/guenlog/exception/ExceptionCode.java
  server/src/main/java/com/seb028/guenlog/member/controller/MemberController.java
  server/src/main/java/com/seb028/guenlog/member/dto/MemberDto.java
  server/src/main/java/com/seb028/guenlog/member/entity/Member.java
  server/src/main/java/com/seb028/guenlog/member/mapper/MemberMapper.java
  server/src/main/java/com/seb028/guenlog/member/repository/MemberRepository.java
  server/src/main/java/com/seb028/guenlog/member/service/MemberService.java
Labels: be-dev

#30 ✨ 마이 페이지 접속 후 개인 정보 불러오는 기능 구현
  server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
  server/src/main/java/com/seb028/guenlog/member/dto/MyPageInfoDto.java
  server/src/main/java/com/seb028/guenlog/member/mapper/MyPageInfoMapper.java
  server/src/main/java/com/seb028/guenlog/member/repository/MemberWeightRepository.java
  server/src/main/java/com/seb028/guenlog/member/service/MemberWeightService.java
Labels: be-dev

#32 ✨ 계획 작성페이지 임시 모달작업
  client/src/assets/11.png
  client/src/assets/1111.png
  client/src/assets/icons.png
  client/src/components/Button.js
  client/src/components/PlanAdd.js
  client/src/components/PlanCalendar.js
  client/src/components/PlanList.js
  client/src/components/PlanModal.js
  client/src/pages/Plan.js
  client/src/reset.css
  client/src/state/states.js
Labels: fe-dev

#33 ⚡️ Plan 컴포넌트 작업
  client/src/components/Button.js
  client/src/components/Plan/Modals/CategorieContent.js
  client/src/components/Plan/Modals/DetailContent.js
  client/src/components/Plan/Modals/DetailListContent.js
  client/src/components/Plan/Modals/PlanModal.js
  client/src/components/Plan/PlanAdd.js
  client/src/components/Plan/PlanCalendar.js
  client/src/components/Plan/PlanList.js
  client/src/components/PlanModal.js
  client/src/pages/Plan.js
  client/src/reset.css
Labels: fe-dev

#37 🐛 메인 달력 임시 수정
  client/src/components/Layout.js
  client/src/components/MainCalendar.js
  client/src/components/Plan/Modals/DetailContent.js
  client/src/components/Plan/Modals/PlanModal.js
  client/src/components/Plan/PlanAdd.js
  client/src/components/Plan/PlanList.js
  client/src/pages/Main.js
  client/src/pages/Plan.js
Labels: fe-dev

#43 ⚡️ Plan 디자인 수정
  client/src/components/Button.js
  client/src/components/MainCalendar.js
  client/src/components/Plan/Modals/CategorieContent.js
  client/src/components/Plan/Modals/DetailContent.js
  client/src/components/Plan/Modals/DetailListContent.js
  client/src/components/Plan/Modals/PlanModal.js
  client/src/components/Plan/PlanCalendar.js
  client/src/components/Plan/PlanList.js
  client/src/components/Plan/RandomMessage.js
  client/src/pages/Plan.js
  client/src/reset.css
Labels: fe-dev

#44 🐛 MapPage 반응형 임시 수정
  client/src/components/Layout.js
  client/src/components/MainCalendar.js
  client/src/components/Map.js
  client/src/components/SearchPlace.js
  client/src/pages/Mappage.js
Labels: fe-dev

#52 🐛 eslint 오류 수정
  client/.eslintrc.js
  client/src/assets/utils.jsx
  client/src/components/Button.jsx
  client/src/components/Layout.jsx
  client/src/components/Plan/Modals/CategorieContent.jsx
  client/src/components/Plan/Modals/DetailContent.jsx
  client/src/components/Plan/Modals/DetailListContent.jsx
  client/src/components/Plan/Modals/PlanModal.jsx
  client/src/components/Plan/PlanAdd.jsx
  client/src/components/Plan/PlanCalendar.jsx
  client/src/components/Plan/PlanList.jsx
  client/src/components/Plan/RandomMessage.jsx
  client/src/pages/NotFound.jsx
  client/src/pages/Plan.jsx
Labels: fe-dev

#55 ✨ user 로그인, jwt 발급 기능 구현
  server/build.gradle
  server/src/main/java/com/seb028/guenlog/config/SecurityConfig.java
  server/src/main/java/com/seb028/guenlog/config/auth/JwtTokenizer.java
  server/src/main/java/com/seb028/guenlog/config/auth/jwt/CustomMemberDetailsService.java
  server/src/main/java/com/seb028/guenlog/config/auth/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/seb028/guenlog/config/auth/jwt/filter/JwtVerificationFilter.java
  server/src/main/java/com/seb028/guenlog/config/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/seb028/guenlog/member/dto/LoginDto.java
  server/src/main/java/com/seb028/guenlog/member/entity/Member.java
  server/src/main/resources/application.yml
Labels: be-dev

#57 ✨ 회원 탈퇴 기능 및 jwt userId 추출 기능 구현
  server/src/main/java/com/seb028/guenlog/config/auth/jwt/filter/JwtVerificationFilter.java
  server/src/main/java/com/seb028/guenlog/member/controller/MemberController.java
  server/src/main/java/com/seb028/guenlog/member/service/MemberService.java
Labels: be-dev

#58 🎨 Member 클래스 수정과 SingleResponseDto 추가로 인한 기존 코드 변경
  server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
  server/src/main/java/com/seb028/guenlog/member/dto/MyPageInfoDto.java
  server/src/main/java/com/seb028/guenlog/member/mapper/MyPageInfoMapper.java
Labels: be-dev

#59 ✨ 마이페이지에서 비밀번호 변경하는 기능
  server/src/main/java/com/seb028/guenlog/exception/ExceptionCode.java
  server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
  server/src/main/java/com/seb028/guenlog/member/dto/PasswordPatchDto.java
  server/src/main/java/com/seb028/guenlog/member/mapper/MyPageInfoMapper.java
  server/src/main/java/com/seb028/guenlog/member/service/MyPageService.java
Labels: be-dev

#61 🐛 마이페이지 개인 정보 수정 기능 진행간 Mapper, DTO 수정
  server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
  server/src/main/java/com/seb028/guenlog/member/dto/MyPageInfoDto.java
  server/src/main/java/com/seb028/guenlog/member/mapper/MyPageInfoMapper.java
Labels: bug, be-dev

#64 ✨ 운동계획 페이지, 메인페이지 api 추가
  server/build.gradle
  server/src/main/java/com/seb028/guenlog/exception/ExceptionCode.java
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseMainController.java
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExercisePlanController.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/CalendarResponseDto.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseMainResponseDto.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExercisePlanRequestDto.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExercisePlanResponseDto.java
  server/src/main/java/com/seb028/guenlog/exercise/entity/Category.java
  server/src/main/java/com/seb028/guenlog/exercise/entity/Exercise.java
  server/src/main/java/com/seb028/guenlog/exercise/entity/Record.java
  server/src/main/java/com/seb028/guenlog/exercise/entity/Today.java
  server/src/main/java/com/seb028/guenlog/exercise/mapper/ExerciseMainMapper.java
  server/src/main/java/com/seb028/guenlog/exercise/mapper/ExercisePlanMapper.java
  server/src/main/java/com/seb028/guenlog/exercise/repository/CategoryRepository.java
  server/src/main/java/com/seb028/guenlog/exercise/repository/RecordListRepository.java
  server/src/main/java/com/seb028/guenlog/exercise/repository/RecordRepository.java
  server/src/main/java/com/seb028/guenlog/exercise/repository/TodayRepository.java
  server/src/main/java/com/seb028/guenlog/exercise/service/ExerciseMainService.java
  server/src/main/java/com/seb028/guenlog/exercise/service/ExercisePlanService.java
  server/src/main/resources/application.yml
Labels: be-dev

#66 ⚡️ Main Calendar 개선 및 서버에 맞춰 수정 작업
  client/.eslintrc.js
  client/package.json
  client/src/components/Main/CalendarContent.jsx
  client/src/components/Main/MainCalendar.jsx
  client/src/components/MainCalendar.jsx
  client/src/components/Plan/PlanCalendar.jsx
  client/src/pages/Main.jsx
Labels: fe-dev

#67 ⚡마이페이지 모달 및 axios코드작성
  client/src/components/Map.jsx
  client/src/components/MyPageFirst.jsx
  client/src/components/MyPageSecond.jsx
  client/src/components/MyPageText.jsx
  client/src/components/PwModal.jsx
  client/src/components/SearchPlace.jsx
  client/src/components/SecessionModal.jsx
  client/src/pages/Mappage.jsx
  client/src/pages/MyPage/Mypage.jsx
Labels: fe-dev

#69 :sparkles: 마이 페이지 접속시 최근 운동기록, 몸무게 기록 확인하는 첫 페이지 기능
  server/src/main/java/com/seb028/guenlog/exercise/repository/TodayRepository.java
  server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
  server/src/main/java/com/seb028/guenlog/member/dto/MyPageResponseDto.java
  server/src/main/java/com/seb028/guenlog/member/mapper/MyPageMapper.java
  server/src/main/java/com/seb028/guenlog/member/repository/MemberWeightRepository.java
  server/src/main/java/com/seb028/guenlog/member/service/MyPageService.java
  server/src/main/java/com/seb028/guenlog/member/util/MonthlyRecord.java
  server/src/main/java/com/seb028/guenlog/member/util/MonthlyWeight.java
  server/src/main/java/com/seb028/guenlog/member/util/MyPage.java
Labels: be-dev

#70 ✨ 최초 로그인 사용자 추가 입력 기능 구현
  server/src/main/java/com/seb028/guenlog/config/SecurityConfig.java
  server/src/main/java/com/seb028/guenlog/config/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/seb028/guenlog/config/auth/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/seb028/guenlog/member/controller/MemberController.java
  server/src/main/java/com/seb028/guenlog/member/dto/MemberDto.java
  server/src/main/java/com/seb028/guenlog/member/entity/Member.java
  server/src/main/java/com/seb028/guenlog/member/mapper/MemberMapper.java
  server/src/main/java/com/seb028/guenlog/member/service/MemberService.java
Labels: be-dev

#71 :bug: 마이 페이지에서 개인 정보 수정시 개인정보에 대한 유효성 검사 추가
  server/src/main/java/com/seb028/guenlog/member/dto/MyPageInfoDto.java
Labels: bug, be-dev

#74 ♻️컴퍼넌트 폴더 정리
  client/src/components/Map/Map.jsx
  client/src/components/Map/SearchPlace.jsx
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/MyPageText.jsx
  client/src/components/Mypage/PwModal.jsx
  client/src/components/Mypage/SecessionModal.jsx
  client/src/pages/Mappage.jsx
  client/src/pages/Mypage.jsx
  client/src/routes/Routes.jsx
Labels: fe-dev

#78 ⚡마이페이지 성능개선
  client/src/components/Map/SearchPlace.jsx
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/MyPageText.jsx
  client/src/components/Mypage/PwModal.jsx
  client/src/components/Mypage/SecessionModal.jsx
  client/src/pages/Mypage.jsx
Labels: fe-dev

#79 ✨ YouTube 임시 작업
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/components/Main/MainCalendar.jsx
  client/src/components/Main/YouTubeContainer.jsx
  client/src/components/Plan/PlanList.jsx
  client/src/components/Plan/RandomMessage.jsx
  client/src/pages/Main.jsx
  client/src/state/states.jsx
Labels: fe-dev

#80 ✨ 운동 진행에서 운동 목록 불러오는 기능
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseProgressController.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressResponseDto.java
  server/src/main/java/com/seb028/guenlog/exercise/mapper/ExerciseProgressMapper.java
  server/src/main/java/com/seb028/guenlog/exercise/service/ExerciseProgressService.java
  server/src/main/java/com/seb028/guenlog/exercise/util/ExerciseProgress.java
Labels: be-dev

#81 🐛 YouTube API 연결 완료 및 로딩처리
  client/src/components/Loading.jsx
  client/src/components/Loding.jsx
  client/src/components/Main/YouTubeContainer.jsx
  client/src/components/Plan/Modals/DetailContent.jsx
  client/src/components/Plan/Modals/PlanModal.jsx
  client/src/components/Plan/RandomMessage.jsx
  client/src/reset.css
Labels: fe-dev

#82 :art: ExercisePlanRequestDto 오타 수정
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExercisePlanRequestDto.java
Labels: be-dev

#84 :art: TodayRepository 테이블 쿼리 대소문자 수정
  server/src/main/java/com/seb028/guenlog/exercise/repository/TodayRepository.java
Labels: be-dev

#85 🐛 사용자 최초 로그인 상태 ResponseBody에 출력
  server/src/main/java/com/seb028/guenlog/config/SecurityConfig.java
  server/src/main/java/com/seb028/guenlog/config/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/seb028/guenlog/member/dto/LoginDto.java
  server/src/main/java/com/seb028/guenlog/member/dto/MemberDto.java
  server/src/main/java/com/seb028/guenlog/member/service/MemberService.java
Labels: be-dev

#87 ✨로그아웃 기능 마이페이지에 추가
  client/package-lock.json
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/MyPageText.jsx
  client/src/components/Mypage/SecessionModal.jsx
  client/src/pages/Logout.jsx
Labels: fe-dev

#88 :art: repository(today,member weight ) 쿼리 수정
  server/src/main/java/com/seb028/guenlog/exercise/repository/TodayRepository.java
  server/src/main/java/com/seb028/guenlog/member/repository/MemberWeightRepository.java
Labels: be-dev

#90 ✨ 운동 진행에서 운동 완료하는 기능
  server/src/main/java/com/seb028/guenlog/exception/ExceptionCode.java
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseProgressController.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressPatchDto.java
  server/src/main/java/com/seb028/guenlog/exercise/entity/Today.java
  server/src/main/java/com/seb028/guenlog/exercise/mapper/ExerciseProgressMapper.java
  server/src/main/java/com/seb028/guenlog/exercise/service/ExerciseProgressService.java
Labels: be-dev

#93 ✨모달창 기능 추가
  client/src/components/Map/SearchPlace.jsx
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/MyPageText.jsx
  client/src/components/Mypage/PwModal.jsx
  client/src/components/Mypage/SecessionModal.jsx
  client/src/pages/Logout.jsx
Labels: fe-dev

#94 ⚡️ 메인페이지 스크롤 애니메이션
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Loading.jsx
  client/src/components/Main/CalendarContent.jsx
  client/src/components/Main/MainCalendar.jsx
  client/src/components/Main/YouTubeContainer.jsx
  client/src/components/Plan/Modals/DetailContent.jsx
  client/src/components/Plan/PlanList.jsx
  client/src/pages/Main.jsx
Labels: fe-dev

#95 ✨ .vscode 폴더 생성
  .vscode/settings.json
  client/.vscode/settings.json
Labels: fe-dev

#97 ✨ Main 페이지 API 작업 완료
  client/.eslintrc.js
  client/src/assets/time.jsx
  client/src/components/Main/CalendarContent.jsx
  client/src/components/Main/MainCalendar.jsx
  client/src/components/Main/YouTubeContainer.jsx
  client/src/state/states.jsx
Labels: fe-dev

#96 :bug: 마이페이지 접속시 운동 기록, 몸무게 기록 조회하는 기능에서 조회안되는 에러 수정, 그외 기타 코드 수정
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseProgressController.java
  server/src/main/java/com/seb028/guenlog/exercise/repository/TodayRepository.java
  server/src/main/java/com/seb028/guenlog/member/dto/MyPageResponseDto.java
  server/src/main/java/com/seb028/guenlog/member/mapper/MyPageMapper.java
  server/src/main/java/com/seb028/guenlog/member/util/MonthlyRecord.java
  server/src/main/java/com/seb028/guenlog/member/util/MonthlyWeight.java
Labels: bug, be-dev

#98 :bug: 운동 진행 목록 조회, 운동 완료 기능시 에러 수정
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseProgressController.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressPatchDto.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressResponseDto.java
  server/src/main/java/com/seb028/guenlog/exercise/mapper/ExerciseProgressMapper.java
  server/src/main/java/com/seb028/guenlog/exercise/service/ExerciseProgressService.java
Labels: bug, be-dev

#101 🐛 로그아웃쪽 버그수정
  client/package-lock.json
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/MyPageText.jsx
  client/src/components/Mypage/PwModal.jsx
  client/src/components/Mypage/SecessionModal.jsx
Labels: fe-dev

#102 🎨get 구조 개선
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/MyPageText.jsx
  client/src/components/Mypage/PwModal.jsx
  client/src/components/Mypage/SecessionModal.jsx
Labels: fe-dev

#103 ✨ google Oauth2 회원가입 기능, Jwt 에러 응답 추가
  server/build.gradle
  server/src/main/java/com/seb028/guenlog/advice/ErrorResponse.java
  server/src/main/java/com/seb028/guenlog/config/SecurityConfig.java
  server/src/main/java/com/seb028/guenlog/config/auth/dto/OauthAttributes.java
  server/src/main/java/com/seb028/guenlog/config/auth/dto/SessionMemberDto.java
  server/src/main/java/com/seb028/guenlog/config/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/seb028/guenlog/config/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/seb028/guenlog/config/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java
  server/src/main/java/com/seb028/guenlog/config/auth/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/seb028/guenlog/config/auth/jwt/filter/JwtVerificationFilter.java
  server/src/main/java/com/seb028/guenlog/config/auth/service/CustomOauth2UserService.java
  server/src/main/java/com/seb028/guenlog/config/auth/utils/ErrorResponder.java
  server/src/main/java/com/seb028/guenlog/member/entity/Member.java
  server/src/main/java/com/seb028/guenlog/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: be-dev

#106 :bug: 회원 탈퇴를 위한 연관관계 맵핑
  server/src/main/java/com/seb028/guenlog/member/entity/Member.java
Labels: be-dev

#107 ✅ Spring Rest Docs API 문서 생성 위한 gradle 설정 및 테스트용 클래스 추가
  server/build.gradle
  server/src/test/java/com/seb028/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
Labels: bug, be-dev

#109 ⚡️ Plan 페이지 axios 생성 구현
  client/src/assets/11.png
  client/src/assets/1111.png
  client/src/components/Loading.jsx
  client/src/components/Main/CalendarContent.jsx
  client/src/components/Main/MainCalendar.jsx
  client/src/components/Main/YouTubeContainer.jsx
  client/src/components/MainCalendar.jsx
  client/src/components/Plan/Modals/CategorieContent.jsx
  client/src/components/Plan/Modals/DetailContent.jsx
  client/src/components/Plan/Modals/DetailListContent.jsx
  client/src/components/Plan/Modals/PlanModal.jsx
  client/src/components/Plan/PlanAdd.jsx
  client/src/components/Plan/PlanCalendar.jsx
  client/src/components/Plan/PlanList.jsx
  client/src/components/Plan/RandomMessage.jsx
  client/src/index.jsx
  client/src/pages/Plan.jsx
  client/src/reset.css
  client/src/state/states.jsx
Labels: fe-dev

#108 :ambulance: PostResponseDto 응답 recordId값 추가
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExercisePlanController.java
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExercisePlanResponseDto.java
  server/src/main/java/com/seb028/guenlog/exercise/mapper/ExercisePlanMapper.java
Labels: be-dev

#110 :truck: ApplicationTest 클래스, ControllerTest 클래스 패키지 이동
  server/src/test/java/com/seb028/guenlog/GuenLogApplicationTests.java
  server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
Labels: bug, be-dev

#114 🎨axios 수정 완료
  client/src/components/Map/Map.jsx
  client/src/components/Mypage/MyPageFirst.jsx
  client/src/components/Mypage/MyPageSecond.jsx
  client/src/components/Mypage/MyPageText.jsx
  client/src/components/Mypage/PwModal.jsx
  client/src/components/Mypage/SecessionModal.jsx
Labels: fe-dev

#116 ✅ 운동 진행 조회 - Controller 테스트, Spring Rest Docs을 이용한 API 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
  server/src/test/java/com/seb028/util/ApiDocumentUtils.java
Labels: documentation, be-dev

#118 :ambulance: 삭제 api 로그 삭제
  server/src/main/java/com/seb028/guenlog/exercise/controller/ExercisePlanController.java
Labels: bug, be-dev

#119 ✅ 운동 진행 완료 - Controller 테스트, Spring Rest Docs을 이용한 API 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressPatchDto.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
Labels: documentation, be-dev

#123 ✅ 마이페이지 조회 API - Controller 테스트, Spring Rest Docs을 이용한 API 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java
Labels: documentation, be-dev

#126 ✨로고 파비콘 추가
  client/public/android-icon-144x144.png
  client/public/android-icon-192x192.png
  client/public/android-icon-36x36.png
  client/public/android-icon-48x48.png
  client/public/android-icon-72x72.png
  client/public/android-icon-96x96.png
  client/public/apple-icon-114x114.png
  client/public/apple-icon-120x120.png
  client/public/apple-icon-144x144.png
  client/public/apple-icon-152x152.png
  client/public/apple-icon-180x180.png
  client/public/apple-icon-57x57.png
  client/public/apple-icon-60x60.png
  client/public/apple-icon-72x72.png
  client/public/apple-icon-76x76.png
  client/public/apple-icon-precomposed.png
  client/public/apple-icon.png
  client/public/browserconfig.xml
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon-96x96.png
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/ms-icon-144x144.png
  client/public/ms-icon-150x150.png
  client/public/ms-icon-310x310.png
  client/public/ms-icon-70x70.png
  client/src/components/Mypage/SecessionModal.jsx
Labels: fe-dev

#127 :bug: Oauth2 로그인 성공시 쿼리로 토큰, 최초 로그인 상태 전송
  server/src/main/java/com/seb028/guenlog/config/SecurityConfig.java
  server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java
Labels: be-dev

#128 :memo: 마이페이지 개인 정보 조회 Controller 테스트 코드 작성 및 Spring Rest Docs API 문서에 마이페이지 개인 정보 조회 API 내용 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java
Labels: documentation, be-dev, be_test

#129 :bug: 서버 배포시 RestDocs Unresolved Error로 인한 코드 수정
  server/src/docs/asciidoc/index.adoc
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
  server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java
Labels: bug, documentation, be-dev, be_test
